import io
import os
import base64
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import qn, nsdecls

# ReportLab imports for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from PIL import Image as PILImage

def generate_txt_file(title: str, content: str) -> io.BytesIO:
    """Generates a UTF-8 text file stream."""
    buffer = io.BytesIO()
    txt_content = f"========================================================================\n"
    txt_content += f"{title.upper()}\n"
    txt_content += f"========================================================================\n\n"
    txt_content += content
    txt_content += f"\n\n========================================================================\n"
    txt_content += f"Generated by LegalEase AI Legal Platform\n"
    txt_content += f"========================================================================\n"
    buffer.write(txt_content.encode('utf-8'))
    buffer.seek(0)
    return buffer

def generate_docx_file(title: str, document_type: str, parties: str, effective_date: str, content: str, terms: str = "", font_name: str = "Times New Roman", logo_base64: str = None) -> io.BytesIO:
    """Generates a professional DOCX document with headers, logo, styled terms table, and signatures."""
    doc = Document()

    # Page margins (1 inch)
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Base Font setup
    style = doc.styles['Normal']
    font = style.font
    font.name = font_name if font_name in ['Times New Roman', 'Arial', 'Georgia', 'Garamond', 'Calibri'] else 'Times New Roman'
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x11, 0x18, 0x27) # Dark charcoal slate

    # Add Logo if present
    if logo_base64:
        try:
            if "," in logo_base64:
                logo_base64 = logo_base64.split(",")[1]
            image_data = base64.b64decode(logo_base64)
            image_stream = io.BytesIO(image_data)
            logo_p = doc.add_paragraph()
            logo_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = logo_p.add_run()
            run.add_picture(image_stream, width=Inches(1.8))
        except Exception as e:
            print(f"[Export DOCX] Logo embedding error: {e}")

    # Header Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_p.paragraph_format.space_after = Pt(18)
    title_run = title_p.add_run(title.upper())
    title_run.font.name = font.name
    title_run.font.size = Pt(18)
    title_run.bold = True
    title_run.font.color.rgb = RGBColor(0x0B, 0x13, 0x2B) # Deep Navy

    # Metadata Box Table
    meta_table = doc.add_table(rows=2, cols=2)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta_table.autofit = False
    
    hdr_cells = meta_table.rows[0].cells
    hdr_cells[0].text = "DOCUMENT SUMMARY"
    hdr_cells[1].text = f"EFFECTIVE DATE: {effective_date}"
    
    row_cells = meta_table.rows[1].cells
    row_cells[0].text = f"Parties Involved:\n{parties}"
    row_cells[1].text = f"Document Type: {document_type}\nJurisdiction: Delaware, USA"
    
    # Style metadata table
    for row in meta_table.rows:
        for cell in row.cells:
            tcPr = cell._tc.get_or_add_tcPr()
            shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="F1F5F9"/>')
            tcPr.append(shd)
            for p in cell.paragraphs:
                p.paragraph_format.space_before = Pt(4)
                p.paragraph_format.space_after = Pt(4)
                for r in p.runs:
                    r.font.size = Pt(9.5)
                    r.font.name = font.name

    doc.add_paragraph().paragraph_format.space_after = Pt(12)

    # Parse and write content line by line with clear heading structure
    lines = content.split("\n")
    for line in lines:
        line_str = line.strip()
        if not line_str:
            continue

        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.line_spacing = 1.15

        # Check if line looks like a major section header
        if any(line_str.startswith(prefix) for prefix in ["1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "RECITALS:", "PARTIES:", "DEFINITIONS", "GOVERNING LAW", "IN WITNESS WHEREOF"]):
            p.paragraph_format.space_before = Pt(12)
            p.paragraph_format.space_after = Pt(6)
            run = p.add_run(line_str)
            run.bold = True
            run.font.size = Pt(12)
            run.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A) # Royal Navy Blue
        else:
            run = p.add_run(line_str)
            run.font.size = Pt(11)

    # Insert Terms Table if terms provided
    if terms:
        doc.add_paragraph().paragraph_format.space_before = Pt(12)
        tbl_heading = doc.add_paragraph()
        tbl_run = tbl_heading.add_run("KEY STIPULATED TERMS BREAKDOWN")
        tbl_run.bold = True
        tbl_run.font.size = Pt(11)
        tbl_run.font.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)

        terms_list = [t.strip() for t in terms.split(";") if t.strip()]
        terms_table = doc.add_table(rows=1, cols=2)
        terms_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        hdr = terms_table.rows[0].cells
        hdr[0].text = "Clause #"
        hdr[1].text = "Stipulation / Requirement"
        
        for idx, term in enumerate(terms_list, 1):
            row = terms_table.add_row().cells
            row[0].text = f"Clause {idx}"
            row[1].text = term
            
        # Style table headers and borders
        for i, row in enumerate(terms_table.rows):
            for cell in row.cells:
                tcPr = cell._tc.get_or_add_tcPr()
                bg_color = "0B132B" if i == 0 else ("F8FAFC" if i % 2 == 1 else "FFFFFF")
                shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{bg_color}"/>')
                tcPr.append(shd)
                for p in cell.paragraphs:
                    for r in p.runs:
                        if i == 0:
                            r.bold = True
                            r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                        r.font.size = Pt(9.5)

    # Footer
    section = doc.sections[0]
    footer = section.footer
    f_p = footer.paragraphs[0]
    f_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    f_run = f_p.add_run(f"LegalEase AI Verified Document | {title} | Confidential")
    f_run.font.size = Pt(8.5)
    f_run.font.color.rgb = RGBColor(0x64, 0x74, 0x8B)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

class NumberedCanvas(canvas.Canvas):
    """ReportLab custom canvas to draw page numbers ('Page X of Y') and formal running footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Draw running top border line on page 2+
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 750, 612 - 54, 750)
            self.drawString(54, 755, "LEGAL EASE AI OFFICIAL DOCUMENT PREVIEW")
        
        # Footer
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 612 - 54, 45)
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawString(54, 32, "LegalEase AI Document Generator | Strictly Confidential")
        self.drawRightString(612 - 54, 32, page_text)
        self.restoreState()

def generate_pdf_file(title: str, document_type: str, parties: str, effective_date: str, content: str, terms: str = "", font_name: str = "Times New Roman", logo_base64: str = None) -> io.BytesIO:
    """Generates a crisp PDF document using ReportLab with headers, footers, logo, tables, and signatures."""
    buffer = io.BytesIO()
    
    # 0.75 in margins
    margin = 54
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin + 10,
        bottomMargin=margin + 10
    )

    styles = getSampleStyleSheet()
    
    # Custom Typography Styles
    body_font = "Helvetica"
    title_font = "Helvetica-Bold"
    if font_name in ["Times New Roman", "Garamond", "Georgia"]:
        body_font = "Times-Roman"
        title_font = "Times-Bold"

    style_title = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName=title_font,
        fontSize=18,
        leading=22,
        alignment=1, # Center
        textColor=colors.HexColor("#0B132B"),
        spaceAfter=15
    )

    style_heading = ParagraphStyle(
        'DocHeading',
        parent=styles['Normal'],
        fontName=title_font,
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#1E3A8A"), # Royal Navy
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )

    style_body = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName=body_font,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6
    )

    style_meta_hdr = ParagraphStyle(
        'DocMetaHdr',
        parent=styles['Normal'],
        fontName=title_font,
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#0F172A")
    )

    style_meta_val = ParagraphStyle(
        'DocMetaVal',
        parent=styles['Normal'],
        fontName=body_font,
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#334155")
    )

    elements = []

    # 1. Logo if uploaded
    if logo_base64:
        try:
            if "," in logo_base64:
                logo_base64 = logo_base64.split(",")[1]
            img_bytes = base64.b64decode(logo_base64)
            img_io = io.BytesIO(img_bytes)
            pil_img = PILImage.open(img_io)
            w, h = pil_img.size
            aspect = h / float(w)
            target_w = 1.8 * inch
            target_h = target_w * aspect
            if target_h > 1.0 * inch:
                target_h = 1.0 * inch
                target_w = target_h / aspect
            
            img_io.seek(0)
            rl_img = Image(img_io, width=target_w, height=target_h)
            rl_img.hAlign = 'CENTER'
            elements.append(rl_img)
            elements.append(Spacer(1, 10))
        except Exception as e:
            print(f"[Export PDF] Logo error: {e}")

    # 2. Main Title
    elements.append(Paragraph(title.upper(), style_title))

    # 3. Metadata Summary Table
    meta_data = [
        [
            Paragraph(f"<b>DOCUMENT TYPE:</b> {document_type}", style_meta_hdr),
            Paragraph(f"<b>EFFECTIVE DATE:</b> {effective_date}", style_meta_hdr)
        ],
        [
            Paragraph(f"<b>PARTIES INVOLVED:</b><br/>{parties}", style_meta_val),
            Paragraph(f"<b>JURISDICTION:</b> Delaware, United States<br/><b>STATUS:</b> Legally Drafted", style_meta_val)
        ]
    ]
    meta_table = Table(meta_data, colWidths=[250, 254])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F1F5F9')),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#0F172A')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 14))

    # 4. Content Paragraphs
    lines = content.split("\n")
    for line in lines:
        l_str = line.strip()
        if not l_str:
            elements.append(Spacer(1, 4))
            continue

        # Check section header
        if any(l_str.startswith(p) for p in ["1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "RECITALS:", "PARTIES:", "DEFINITIONS", "GOVERNING LAW", "IN WITNESS WHEREOF"]):
            elements.append(Paragraph(l_str, style_heading))
        else:
            # Escape XML entities for ReportLab Paragraph
            safe_text = l_str.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            elements.append(Paragraph(safe_text, style_body))

    # 5. Terms Table if present
    if terms:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("KEY STIPULATED TERMS SUMMARY", style_heading))
        terms_list = [t.strip() for t in terms.split(";") if t.strip()]
        
        table_rows = [[
            Paragraph("<b>Clause</b>", style_meta_hdr),
            Paragraph("<b>Stipulated Terms & Conditions</b>", style_meta_hdr)
        ]]
        for idx, term in enumerate(terms_list, 1):
            table_rows.append([
                Paragraph(f"Clause {idx}", style_meta_val),
                Paragraph(term.replace('&', '&amp;'), style_body)
            ])
            
        terms_tbl = Table(table_rows, colWidths=[80, 424])
        terms_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (1,0), colors.HexColor('#0B132B')),
            ('TEXTCOLOR', (0,0), (1,0), colors.white),
            ('PADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#F8FAFC'), colors.white]),
        ]))
        elements.append(terms_tbl)

    # Build document
    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
